import numpy as np 
import matplotlib.pyplot as plt

a = np.loadtxt('part.dat')
f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)
plt.plot(a[:,0], a[:,1], label='<H>')
#plt.axhline(0, c='grey', alpha=0.5, ls='--')
#plt.xlim([0,100])
plt.xlabel("iterations", fontsize=20)
plt.ylabel(r'$e ^{-\beta H}$' , fontsize=20)
plt.title(r"'$e ^{-\beta H}$' value  of $H = \frac{p^2}{2m} + \frac{1}{2}m\omega^2x^2 - \frac{p}{m}$", fontsize=20)
plt.legend()
plt.show()

f = plt.figure()
f.set_figwidth(10)
f.set_figheight(8)
plt.plot(a[:,0], a[:,1], label='<H>')
#plt.axhline(0, c='grey', alpha=0.5, ls='--')
#plt.xlim([0,100])
plt.xlabel("iterations", fontsize=20)
plt.ylabel("$\exp(-\beta$ H)", fontsize=20)
plt.title(r"'$e ^{-\beta H}$' value  of $H = \frac{p^2}{2m} + \frac{1}{2}m\omega^2x^2 - \frac{p}{m}$", fontsize=20)
plt.legend()
plt.savefig("part.pdf")